name: Rustdoc

on: [push, pull_request]

permissions:
  contents: read


jobs:
  rdme:
    name: cargo rdme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - run: cargo install cargo-rdme
      - run: cargo rdme --check

  rustdoc:
    name: cargo doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
          toolchain: 1.86.0
      - run: sudo apt-get update && sudo apt-get install -y pkg-config libtss2-dev
      - run: cargo doc --no-deps --all-features
